# Generated by Django 5.1.4 on 2024-12-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
