# Generated by Django 4.2.13 on 2024-12-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_alter_personneladministratif_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=50),
        ),
    ]
