# Generated by Django 4.2.13 on 2024-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DossierDeCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('emploi_tuteur', models.CharField(max_length=255)),
                ('revenu_tuteur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personnes_charge', models.IntegerField()),
                ('cin_upload', models.FileField(upload_to='uploads/cin/')),
                ('revenu_upload', models.FileField(upload_to='uploads/revenu/')),
                ('attestation_habitation', models.FileField(upload_to='uploads/habitation/')),
                ('bac_upload', models.FileField(upload_to='uploads/bac/')),
                ('ville_habitation', models.CharField(max_length=255)),
                ('ville_etude', models.CharField(max_length=255)),
                ('niveau_etude', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
