# Generated by Django 4.2.13 on 2024-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EspaceETD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierdecandidature',
            name='attestation_habitation',
        ),
        migrations.RemoveField(
            model_name='dossierdecandidature',
            name='cin_upload',
        ),
        migrations.RemoveField(
            model_name='dossierdecandidature',
            name='niveau_etude',
        ),
        migrations.RemoveField(
            model_name='dossierdecandidature',
            name='revenu_upload',
        ),
        migrations.AddField(
            model_name='dossierdecandidature',
            name='attestation_habitation_file',
            field=models.FileField(blank=True, null=True, upload_to='attestations_habitation/'),
        ),
        migrations.AddField(
            model_name='dossierdecandidature',
            name='cin_file',
            field=models.FileField(blank=True, null=True, upload_to='cin_files/'),
        ),
        migrations.AddField(
            model_name='dossierdecandidature',
            name='niveau',
            field=models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat')], default='licence', max_length=20),
        ),
        migrations.AddField(
            model_name='dossierdecandidature',
            name='revenu_file',
            field=models.FileField(blank=True, null=True, upload_to='revenu_files/'),
        ),
        migrations.AlterField(
            model_name='dossierdecandidature',
            name='bac_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/bac/'),
        ),
    ]
